MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './pretrained/resnet101_ibn_a-59ea0ac6.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'resnet101_ibn_a'
  NO_MARGIN: True
  DEVICE_ID: ('0')

INPUT:
  SIZE_TRAIN: [320, 320]
  SIZE_TEST: [320, 320]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('aic')

DATALOADER:
  SAMPLER: 'softmax'
  NUM_INSTANCE: 8
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 80
  BASE_LR: 0.01
  IMS_PER_BATCH: 64
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 80
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  FP16_ENABLED: True

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: False
  RE_RANKING_TRACK: True
  WEIGHT: './logs/camera/resnet101_ibn_a_80.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
  EVAL: True
  FIC: True
OUTPUT_DIR: './logs/camera'
