CHALLENGE_DATA_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/AIC22_Track1_MTMC_Tracking/'
DET_SOURCE_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/detection/images/test/S06/'
DATA_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/detect/'

REID_SIZE_TEST: [384, 384]
ROI_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/AIC22_Track1_MTMC_Tracking/test/S06/'
CID_BIAS_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/AIC22_Track1_MTMC_Tracking/cam_timestamp/'
USE_RERANK: True
USE_FF: True
SCORE_THR: 0.1
MCMT_OUTPUT_TXT: 'track1.txt'
MCMT_Interpo_OUTPUT_TXT: 'track1_interpolation.txt'