DET_SOURCE_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/detection/images/test/S06/'
REID_MODEL: 'reid_model/resnext101_ibn_a_2.pth'
REID_BACKBONE: 'resnext101_ibn_a'
DET_IMG_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/detect/'
DATA_DIR: '/home/gaoyansong/AICITY2022_Track1_TAG/datasets/detect_reid2/'
REID_SIZE_TEST: [384, 384]
